name: Deployment

on:
  push:

jobs:
  info:
    env:
      INFO: ${{ secrets.INFO }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Info
        run: |
          echo $INFO
          echo ${{ secrets.INFO }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Run tests
        run: npm run test
  Deployment:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Echo
        run: echo "Build successful"
