name: Info

on:
  issues:
    types:
      - opened

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Info
        run: echo ${{ github.event.issue.title }}
